version: '3.1'

services:

  db:
    image: postgres:15.3
    restart: always
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080